- css/poole.css
As discussed in #11. Added two lines for <code>.highlight</code> in <code>poole.css</code> that puts a horizontal slidebar to preformatted text and prevent (unwanted) line breaks, if it is neccessary.
> Issue 11: Adjust page width for wide examples

- wiki/Reading_large_PDB_files.md
The recipe did not work as published; it runs into errors trying to find Residue. This can be fixed by adding in the correct imports, as explained by Peter Cock and Markus Piotrowski in http://lists.open-bio.org/pipermail/biopython/2016-May/015944.html.
> Fixed imports for xpdb 

- wiki/Category_Cookbook.md
- wiki/Category_Wiki_Documentation.md
- wiki/Documentation.md
The main Wiki page (`Category:Wiki_Documentation`) was only reachable from the main page but not from `Documentation`
> More prominent link to Wiki main page

- index.md
I knew about the migration from MediaWiki to Github, yet when I visited biopython.org, it was really unobvious how to get to the wiki. It seemed to me like the first link on the Placeholder Welcome page should take me there, but that took me to a Github project.  Meanwhile, the actual link was not very descriptive and visually indistinguishable from the notice's text (that is, it looked like it's just another part of the notice). The notice is for the largely technical issue of where the wiki is hosted; most visitors just want to get straight to the wiki (although I recognize the importance of having this notice in the first place in order to inform visitors of potential issues). 
Anyway, I rephrased things a little bit to clarify where each link leads and I added a horizontal rule to …
> Clarify the placeholder welcome 

- wiki/SeqIO.md
opening files with the "with" statement is more secure since the file is *always* closed, even if the script crashes. It also saves one extra line of code ("handle.close()")
> using "with"-statement to open files

- wiki/ACE_contig_to_alignment.md
- wiki/Active_projects.md
- wiki/AlignIO.md
- wiki/Annotate_Entrez_Gene_IDs.md
- wiki/BioGeography.md
- wiki/BioSQL.md
- wiki/BioSQL_Windows.md
- wiki/Building_a_release.md
- wiki/Concatenate_nexus.md
- wiki/Contributing.md
- wiki/Converting_sequence_files.md
- wiki/Coordinate_mapping.md
- wiki/Gene_Ontology.md
- wiki/Gene_predictions_to_protein_sequences.md
- wiki/Intergenic_regions.md
- wiki/List_of_applications_executed_via_Biopython.md
- wiki/MotifDev.md
- wiki/PAML.md
- wiki/PhyloXML.md
- wiki/Phylo_cookbook.md
- wiki/PopGen_dev.md
- wiki/PopGen_dev_Statistics.md
- wiki/ProtParam.md
- wiki/Publications.md
- wiki/Reading_from_unix_pipes.md
- wiki/Reading_large_PDB_files.md
- wiki/Remove_PDB_disordered_atoms.md
- wiki/Seq.md
- wiki/SeqRecord.md
I've changed the title of all the .md files that were 9 months old.
> Titles updated

- wiki/Continuous_integration.md
Caveat: the top of this page says it may be deleted and I don't closely follow the details of the CI.
Mostly formatting changes.
I could not find an obvious replacement for this broken link:
http://www.apparatusproject.org/blog/2009/06/github-and-buildbot-continuous-integration/
I preserved the link in a comment. [StackOverflow](http://stackoverflow.com/a/20885980/1547619) says that 
``` markdown
[//]: # (comment)
```
will create a code comment in markdown that will not be rendered in the HTML.
> Continuous integration

- assets/css/hyde.css
When the browser is resized, I noticed that the footer interferes with the main menu as observed below - 
This can be attributed to the bottom margin set in hyde.css - 
`.sidebar-footer {
position: absolute;
bottom: 5px;
padding: 1rem;
}`
and is fixed on removal without causing issues to other views.
> Fixing the sidebar footer for different browser sizes

- wiki/Download.md
- wiki/Packages.md
This moves a large chunk of the downloads page into its own new page, and documents using conda #118.
Cross reference https://github.com/biopython/biopython/issues/1295
> Move packages info to its own page

- wiki/SourceCode.md
Since we moved to GitHub development discussion in January 2018 we
should point to the main discussion list on the Source Code page.
See <https://biopython.org/wiki/Mailing_lists>
> Update mailing list link

- wiki/Building_a_release.md
- wiki/Continuous_integration.md
- wiki/Contributing.md
- wiki/Deprecation_policy.md
- wiki/MotifDev.md
- wiki/SourceCode.md
- wiki/The_Biopython_Structural_Bioinformatics_FAQ.md
Since biopython-dev@biopython.org mailing list is closed since January 2018. We should change to biopython@biopython.org mailing list in the whole site.
> Update mailing list link globally

- wiki/GitUsage.md
- wiki/SourceCode.md
GitUsage guide contains several deadlinks and need to be fixed. I propose to remove obsolete ones and update those moved to different sites.
> Fix deadlinks

- wiki/GitUsage.md
- wiki/SourceCode.md
There are outdated urls in GitUsage document, i.e., http->https, changed  domain, etc.
I propose to remove links pointing to obsolete webpages such as 
http://zrusin.blogspot.com/2007/09/git-cheat-sheet.html
I'm not sure whether the fork-queue feature is still supported by GitHub. If not I would suggest to remove 
https://github.com/blog/270-the-fork-queue
and rewrite the paragraph accordingly.
> Update outdated links in GitUsage

- wiki/Scriptcentral.md
snpFC is a tool for filtering SNP records using threshold values and for comparing SNP records from two or more VCF files to get common and unique SNP records.
> snpFC tool added

- wiki/GitUsage.md
This PR expands the `GitUsage` page with details on how to set up and use `flake8` for style-checking.
> Explain how to setup and use flake8

- wiki/BioSQL.md
When running `mysqladmin -u root create biosqldb` with MySQL as 5.7.27-0 on Ubuntu 18.04, I got a warning saying  `mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost''`. 
This problem seems to be that new mysql takes use of the `auth_socket` plugin if the password is left empty while installing. Answers from [stackoverflow](https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost) suggest a password is required. Therefore, I changed the codes here for compatibility with the new version of mysql. 
**These codes were only tested on Ubuntu 18.04.**
> Improve compatibility with new version of mysql

- wiki/Documentation.md
Added a link to a notebook version of the tutorial (adapted) to the documentation.
This was discussed in https://github.com/biopython/biopython/issues/2808
> added link to notebooks based on the tutorial for documentation

- wiki/SeqRecord.md
Letter mistake - line 132 instead of "tpye" instead of "type"
> Letter mistake in 132 line

- wiki/Building_a_release.md
This commit updates the build instructions as per biopython/biopython#2904 to drop the reference to updating the version number in `Tutorial.tex` as well as updating heavea and biopython version numbers.
> Updated build instructions

- wiki/Alphabet.md
Intended to replace https://github.com/biopython/biopython/issues/3156 as a place to direct people on code changes from the removal of `Bio.Alphabet` in Biopython 1.78
> Page about Bio.Alphabet removal

- _includes/head.html
`site.baseurl` is not directing to the 'root' URL (any longer). Thus replace with `relative_url`.
This will close #179
> Replace 'site.baseurl' with relative_url filter

- wiki/SeqIO.md
"rU" was deprecated in Python 3.4, so it is not needed. For Python 3.4+, "rU" will give deprecation error.
> Deprecation of "rU"

- wiki/Download.md
The old link : [http://numpy.scipy.org/](http://numpy.scipy.org/) is updated to the new link : [https://numpy.org/](https://numpy.org/) .
Please consider and review PR.... Thank You
> Updated a NumPy Link

- wiki/Phylo_cookbook.md
itertools no longer uses *.next() call
izip() is depreciated and replaced by built in zip()
> Fix a depreciated example

- wiki/Multiple_Alignment_Format.md
The previous link fetched the human chr10; the following tutorial errors out with the human file.
> Fixed link to UCSC to correct file

- wiki/The_Biopython_Structural_Bioinformatics_FAQ.md
I was having an issue following along with the code on this page. When I only ran the code as it was described, I would get this error:
```
>>> MMCIF2Dict("5SWE.Cif")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```
Earlier in the wiki page, you're told to run `from Bio.PDB import *`, which imports the _**module**_ of `MMCIF2Dict`, but not the class. So I updated the doc since I I think this is actually the second time I've landed on this page and experienced this problem.
> Add correct import statement to FAQ
