wiki/Documentation.md
=> Fixed a few extarnal links External links

wiki/Active_projects.md, wiki/BioGeography.md, wiki/GitUsage.md, wiki/User_Matzke.md
Fixing external links issue #32
=> more External links

wiki/List_of_applications_executed_via_Biopython.md
Needed only a little work, created an issue to look more closely at the details of the page, is it complete?
issue #40 and issues #38
=> List of applications executed via biopython

wiki/Contributing.md
- Updated Redmine link to point to GitHub, rephrased language slightly #48 
- Removed broken link (pre-PEP8)
- Copy editing
=> Contributing

wiki/ACE_contig_to_alignment.md, wiki/BioGeography.md, wiki/Building_a_release.md, wiki/Continuous_integration.md, wiki/Deprecation_policy.md, wiki/GitMigration.md, wiki/GitUsage.md, wiki/Mailing_lists.md, wiki/Multiple_Alignment_Format.md, wiki/Publications.md, wiki/Sequence_Cleaner.md, wiki/SourceCode.md, wiki/The_Biopython_Structural_Bioinformatics_FAQ.md, wiki/User_Alexl.md, wiki/User_Jblucks.md
=> Carefully  Change biopython to Biopython, github to GitHub,.

wiki/PopGen.md, wiki/PopGen_Genepop.md, wiki/PopGen_dev.md, wiki/PopGen_dev_Statistics.md
Minor (mostly cosmetic) changes to PopGen pages
=> PopGen pages

wiki/Biopython.md
Two links updated
- Link pointing to the RSS feed (instead of the OBF News page)
- LICENSE link
=> First pull request from 'Edit this page' button

wiki/Google_Summer_of_Code.md, wiki/User_EricTalevich.md
=> Update etal's website links to point to GitHub

wiki/Ace_contig_class.md
=> Update Ace_contig_class.md title

wiki/Converting_sequence_files.md, wiki/Sequence_Cleaner.md, wiki/Split_large_file.md
Hi,
I took the liberty to go through the Cookbook examples and correct the file handling parts as suggested in issue #353.
=> editing for issue #353

wiki/Download.md
Show ```-upgrade``` option of pip for updating an existing Biopython version
=> Update Download: Show upgrade option of pip

wiki/The_Biopython_Structural_Bioinformatics_FAQ.md
See https://github.com/biopython/biopython/issues/1331.
=> Reference to nglview integration

wiki/Mailing_lists.md
Make it clearer that you need to subscribe before sending to the mailing lists.
=> You have to subscribe to post to the mailing lists

wiki/Participants.md
Just some changes in my details.
=> Participants.md: change details for Michael Hoffman

wiki/Documentation.md
The documentation for the cluster module has been integrated into the Biopython Tutorial and Cookbook.
=> Bio.Cluster documentation

wiki/SeqIO.md
Added separate usage info for python3:
https://stackoverflow.com/a/1073407/310453
=> next() function should be used in python3

wiki/Active_projects.md
Per https://github.com/biopython/biopython/issues/1221#issuecomment-362805384, I believe this particular task was finished early last year.
=> Eliminate an obsolete item from the "Current projects" page

wiki/Deprecation_policy.md
Adding more detail, explaining the policy is used for modules, methods, functions and classes.
=> Explaining the policy is used for modules, methods, functions.

wiki/Download.md
Updated version on download page, to 1.75.
=> Updated version on download page, to 1.75.

wiki/Documentation.md
As suggested in https://github.com/biopython/biopython/issues/2808
=> Add link to biopython-coronavirus tutorial notebook

wiki/GitUsage.md
Small fix just in case it engendered confusion.
=> fix: Typo fix on line #22

wiki/GFF_Parsing.md
There's a small syntax error in the code example - a close quote at the beginning of the comment. Also, I have some ideas on how to further improve this section of the docs and that will be in a separate PR.
=> Tiny syntax error :)

_config.yml, wiki/Biopython.md, wiki/Building_a_release.md, wiki/Documentation.md, wiki/Download.md
gh-pages update for the1.77 release
=> Update for 1.77 release

wiki/Active_projects.md
=> Updated the outdated link of sphinx

wiki/Gene_Ontology.md, wiki/Phylo.md
Addresses the same issue pointed out in biopython/biopython#3137
* Fix links to networkx and pygraphviz
=> Fix broken links to networkx and pygraphviz

wiki/Building_a_release.md
This pull requests partially addresses biopython/biopython#3238 by updating the release page to include details on building and uploading the PDB FAQ.
=> Update building a release to include FAQ

_config.yml, wiki/Biopython.md, wiki/Building_a_release.md, wiki/Documentation.md, wiki/Download.md
Updated files for 1.78 release
=> Update website 1.78 release

wiki/Contributing.md
Fixed typo - converted be to by on line 127
=> Fixed typo

_config.yml, _includes/head.html
Follow-on PR, according to discussion on #180 
Does seem to work, applied here: https://markuspiotrowski.github.io/
=> Use relative_url filter consistently and set baseurl to empty

wiki/BioSQL.md
Changes summary:
- Specified database software packages for python 2/3 and Ubuntu
- Adds info on installing database drivers and their names for python 2/3
=> Update BioSQL wiki for Python2/3 and Ubuntu versions 

wiki/BioSQL.md
=> More BioSQL updates

wiki/Split_large_file.md
This should improve readability.
=> include list() in code formatting block

wiki/Phylo_cookbook.md
Updating Numpy references to documentation recommended.
https://github.com/biopython/biopython/issues/4238#issue-1589352538
Licensed under Biopython License Agreement and 3-Clause BSD License
=> Update Phylo_cookbook.md documentation to numpy standard

wiki/Category_Cookbook.md
to compliment: to praise
to complement: to add information to
=> Update Category_Cookbook.md typo

wiki/Active_projects.md
Fixed a typo in the Active_projects title.
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.
`NEWS.rst` and `CONTRIB.rst` as part of this pull request, am listed
already, or do not wish to be listed. (_This acknowledgement is optional._)
=> Fixed a typo
